# Generated by Django 5.2.8 on 2025-11-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrawingFeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='drawing',
            unique_together={('name', 'artist')},
        ),
    ]
