# Generated by Django 5.2.8 on 2025-11-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrawingFeed', '0002_alter_artist_name_alter_drawing_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='image',
            field=models.ImageField(upload_to='drawings/'),
        ),
    ]
